In [1]:
#importing numpy
import numpy as np

In [8]:
#creating  array
my_list = [1,2,3]
my_list

[1, 2, 3]

In [9]:
np.array(my_list)

array([1, 2, 3])

In [10]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [11]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
#BUILD-IN METHOD


In [13]:
#ARRANGE-Return evenly spaced values within a given interval.

In [14]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [16]:
#ZEROES AND ONES -Generate arrays of zeros or ones


In [17]:
np.zeros(3)

array([0., 0., 0.])

In [18]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [19]:
np.ones(3)

array([1., 1., 1.])

In [20]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [21]:
#LINSPACE:-Return evenly spaced numbers over a specified interval.

In [22]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [23]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [24]:
#EYE-Creates an identity matrix

In [25]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [27]:
#RANDOM-Numpy also has lots of ways to create random number arrays:



In [29]:
#rand-Create an array of the given shape and populate it with random samples from a uniform distribution over [0, 1).

In [28]:
np.random.rand(2)

array([0.67067969, 0.57394521])

In [30]:
np.random.rand(5,5)

array([[0.62746861, 0.85546049, 0.01022004, 0.55981794, 0.92872404],
       [0.63484418, 0.68096444, 0.60807989, 0.25575224, 0.85080532],
       [0.02708784, 0.3430867 , 0.6084449 , 0.37982675, 0.40416851],
       [0.5735597 , 0.39889498, 0.31536639, 0.05344009, 0.57927658],
       [0.94963595, 0.12666394, 0.0615271 , 0.37947457, 0.67761296]])

In [31]:
# randn-Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

In [32]:
np.random.randn(2)

array([0.10138487, 0.72855609])

In [33]:
np.random.randn(5,5)

array([[ 0.31536034,  0.89442074, -0.37943961, -1.40980977,  1.98903296],
       [ 0.10730968, -0.5494241 ,  0.14281992,  1.41349174, -0.98332812],
       [ 1.49248777,  0.31044538,  0.52642189,  0.18267476, -0.79392028],
       [ 1.86646009, -0.72046384,  0.48261207,  0.51317068, -0.68039589],
       [ 0.94278978, -0.89643289, -1.21548349,  0.38455095,  0.64571673]])

In [34]:
#randint-Return random integers from low (inclusive) to high (exclusive).

In [35]:
np.random.randint(1,100)

77

In [36]:
np.random.randint(1,100,10)

array([99, 65,  9, 38, 28, 50, 29, 20, 71, 57])

In [37]:
#ARRAY ATTRIBUTES AND METHODS

In [38]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [39]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [40]:
ranarr

array([35, 33, 10, 21, 14,  1,  6, 23, 33, 49])

In [42]:
#RESHAPE-Returns an array containing the same data with a new shape.


In [43]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [44]:

# max,min,argmax,argmin-These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax.

In [45]:
ranarr

array([35, 33, 10, 21, 14,  1,  6, 23, 33, 49])

In [46]:
ranarr.max()

49

In [47]:
ranarr.argmax()

9

In [48]:
ranarr.min()

1

In [49]:
ranarr.argmin()

5

In [52]:
#Shape-Shape is an attribute that arrays have (not a method):

In [53]:
# Vector
arr.shape

(25,)

In [54]:
# Notice the two sets of brackets
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [55]:
arr.reshape(1,25).shape

(1, 25)

In [56]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [57]:
arr.reshape(25,1).shape

(25, 1)

In [58]:
#dtype-You can also grab the data type of the object in the array:

In [59]:
arr.dtype

dtype('int32')